Nueva versión del LiveTV-TS que sustituye al liveTV+10

diff --git a/htdocs/cgi-bin/crid/tsView b/htdocs/cgi-bin/crid/tsView
--- a/htdocs/cgi-bin/crid/tsView
+++ b/htdocs/cgi-bin/crid/tsView
@@ -8,52 +8,98 @@ port=`echo $QUERY_STRING | cut -d"&" -f2 | cut -d"=" -f2`
 user=`echo $QUERY_STRING | cut -d"&" -f3 | cut -d"=" -f2`
 pwd=`echo $QUERY_STRING | cut -d"&" -f4 | cut -d"=" -f2`
 mplayer=`echo $QUERY_STRING | cut -d"&" -f5 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\//g' | sed -e 's/+/ /g' | sed -e 's/%2F/\//g'`
-tmpdir=`echo $QUERY_STRING | cut -d"&" -f6 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\//g' | sed -e 's/%2F/\//g'`
+tmpdir=`echo $QUERY_STRING | cut -d"&" -f6 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\\\/g' | sed -e 's/%2F/\//g'`
 aspect=`echo $QUERY_STRING | cut -d"&" -f7 | cut -d"=" -f2`
-so=`echo $QUERY_STRING | cut -d"&" -f8 | cut -d"=" -f2`
+#so=`echo $QUERY_STRING | cut -d"&" -f8 | cut -d"=" -f2`
 
-mplayerOptions="-cache 2048 -quiet -noaspect -aspect $aspect -autosync 30 -framedrop -ni"
+mplayerOptions="-cache 4096 -quiet -noaspect -aspect $aspect -autosync 30 -framedrop"
 
-fmpg=`./getfmpgts`
-if [ "$fmpg" != "" ]; then
-    plsfile=$tmpdir/mplayer_temp_`date +%s`.pls
-    
-    echo "Content-type: application/octet-stream"
-    if [ $so -eq 1 ] ; then
-        echo "Content-Disposition: attachment; filename=verTS.cmd"
-        echo ""
-        echo "@echo off > $plsfile"
-        i=0
-        while [ $i -lt 30 ]
-        do
-            if [ $i -lt 10 ]; then
-                echo "echo ftp://$user:$pwd@$host:$port${fmpg}.00$i.mpg >> $plsfile"
-            else
-                echo "echo ftp://$user:$pwd@$host:$port${fmpg}.0$i.mpg >> $plsfile"
-            fi
-            i=$((i+1))
-        done    
-        echo "\"$mplayer\" $mplayerOptions -playlist $plsfile"
-    else
-        echo "Content-Disposition: attachment; filename=verTS.sh"
-        echo ""
-        echo "#!/bin/sh"
-        echo "rm -f $plsfile"
-        echo "touch $plsfile"
-        i=0
-        while [ $i -lt 30 ]
-        do
-            if [ $i -lt 10 ]; then
-                echo "echo \"ftp://$user:$pwd@$host:$port${fmpg}.00$i.mpg\" >> $plsfile"
-            else
-                echo "echo \"ftp://$user:$pwd@$host:$port${fmpg}.0$i.mpg\" >> $plsfile"
-            fi
-            i=$((i+1))
-        done    
-        echo "$mplayer $mplayerOptions -playlist $plsfile"
-    fi
-else
-    echo "Content-type: text/plain"
-    echo ""
-    echo "ERROR: No se ha encontrado fichero de TimeShift"
-fi
+function dos () {
+	echo $2
+}
+DIR_MPG=`dos \`grep "DeviceRecordingFolder" /var/etc/settings.txt\``
+#RecordingFolder=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt`
+plsfile=$tmpdir/mplayer_temp_`date +%s`.pls
+
+#if [ $so -eq 0 ] ; then
+#	#echo Linux/Unix
+#	echo "Content-type: application/octet-stream"
+#	echo "Content-Disposition: attachment; filename=verts.sh"
+#	echo ""
+#	echo "#!/bin/bash"
+#	echo "echo Iniciando..."
+#	echo USUARIO="$user"
+#	echo PASS="$pwd"
+#	echo HOST="$host"
+#	echo FTP_PORT="$port"
+#	echo BASE_URL="http://\$HOST"
+#	echo TEMP=\"$tmpdir\"
+#	echo MPLAYER=\"$mplayer\"
+#	echo OPCIONES_MPLAYER=\"$mplayerOptions\"
+#	echo CADENA_FTP="ftp://\$USUARIO:\$PASS@\$HOST:\$FTP_PORT:"
+#	echo 
+#	echo EJECUTAR=1
+#	echo "while [ \$EJECUTAR -eq "1" ] ; do"
+#		echo "echo -n \$CADENA_FTP > \$TEMP/ultmpg"
+#		echo "wget -q -O - \$BASE_URL/cgi-bin/box/ultmpg?$DIR_MPG >> \$TEMP/ultmpg"
+#		echo "cat \$TEMP/ultmpg"
+#		echo "\$MPLAYER \$OPCIONES_MPLAYER -playlist \$TEMP/ultmpg"
+#		echo "if [ \$? -eq 1 ] ; then  #error o se ha pulsado Ctr-c"
+#			echo "EJECUTAR=0"
+#		echo "fi"
+#	echo "done"
+#else
+	echo "Content-type: application/octet-stream"
+	echo "Content-Disposition: attachment; filename=verts.cmd"
+	echo ""
+	echo "@ECHO OFF"
+	echo "echo Iniciando..."
+	echo SET USUARIO="$user"
+	echo SET PASS="$pwd"
+	echo SET HOST="$host"
+	echo SET FTP_PORT="$port"
+	echo SET BASE_URL="http://%HOST%"
+	echo SET TEMP="$tmpdir"
+	echo SET MPLAYER="$mplayer"
+	echo SET OPCIONES_MPLAYER="$mplayerOptions"
+	echo SET CADENA_FTP="ftp://%USUARIO%:%PASS%@%HOST%:%FTP_PORT%"
+    echo "echo @echo off > .\start_mplayer.cmd"
+	echo "echo echo Llenando el buffer de MPlayer con wget. Espera unos segundos .... >> .\start_mplayer.cmd"
+	echo "echo sleep 15 >> .\start_mplayer.cmd"
+	ultmpg=`./getmpgts`
+	i=`echo $ultmpg | cut -d"." -f3`
+	i=$((i+1-1))
+	fmpg=`echo $ultmpg | cut -d"." -f1`.fmpg
+    while [ $i -lt 40 ]
+    do
+        if [ $i -lt 10 ]; then
+            echo "echo ${fmpg}.00$i.mpg >> $plsfile"
+        else
+            echo "echo ${fmpg}.0$i.mpg >> $plsfile"
+        fi
+        i=$((i+1))
+    done
+	echo "echo \"%MPLAYER%\" %OPCIONES_MPLAYER% -playlist $plsfile >> .\start_mplayer.cmd"
+	echo "echo del /f /q $tmpdir\*.mpg >> .\start_mplayer.cmd"
+	echo "echo del /f /q $tmpdir\*.pls >> .\start_mplayer.cmd"
+	echo "echo exit >> .\start_mplayer.cmd"
+	echo "start \"MPlayer\" /min .\start_mplayer.cmd"
+	echo ":bucle"
+    echo "wget -q -O - %BASE_URL%/cgi-bin/crid/getmpgts?$DIR_MPG > %TEMP%\ultmpg"
+	echo "SET /P FICHERO=<%TEMP%\ultmpg"
+	echo "SET NOMBRE_COMPLETO=%CADENA_FTP%$DIR_MPG/%FICHERO%"
+	echo "goto inicio"
+	echo ":recargar"
+	echo "sleep 8"
+	echo ":inicio"
+	echo "wget --continue --passive-ftp -P $tmpdir %NOMBRE_COMPLETO%"
+	echo "wget -q -O - http://$host/cgi-bin/crid/getfilesize?$DIR_MPG/%FICHERO% > $tmpdir/filesize.tmp"
+	echo "sleep 1"
+	echo "SET /P FILE_SIZE_GIGA=<$tmpdir\filesize.tmp"
+	echo "wc -c $tmpdir\%FICHERO% | cut -d c -f 1 > $tmpdir\filesize2.tmp"
+    echo "SET /P FILE_SIZE_PC=<$tmpdir\filesize2.tmp"
+    echo "wget -q -O - http://$host/cgi-bin/crid/checkfilesizes?%FILE_SIZE_GIGA%-%FILE_SIZE_PC% > $tmpdir/checksize.tmp"
+	echo "SET /P CHECK_SIZE=<$tmpdir\checksize.tmp"
+    echo "if \"%CHECK_SIZE%\" == \"NO\" goto recargar"
+    echo "goto bucle"
+#fi
